### ISSUE TITLE
what is the right redirect URL ?

### ISSUE THREAD

**Issue by saket424** [tmunzer/SchoolControl#12]
https://127.0.0.1:3443/conf/api/reg did not seem to get the list of APs that are registered with HiveManager NG. In my case I have only one AP and the example does not populate the Devices tab.

**Comment by tmunzer** [comment]
Hi Saket424. The redirect URL is used for OAuth only. 
So you first have to create an account on the [Aerohive Developer Portal](http://developer.aerohive.com/), and create an "application" here. This will give you a clientID, a secretID, and let you configure the redirectURL (this will more or less allow the Aerohive Cloud to identify your application).
Then you'll have to put these information into the "config" file.

If you are running the app on your laptop, the redirectURL should be something like "https://localhost:3443/api/oauth/reg"

**Comment by saket424** [comment]
Some more progress -- now i get a little further when I use the redirecturl that you suggested "https://localhost:3443/api/oauth/reg"

error: invalid_client_details
info: ::1 - - [Thu, 12 Apr 2018 15:06:15 GMT] "GET /api/oauth/reg?error=invalid_client_details HTTP/1.1" 200 991 "https://cloud.aerohive.com/thirdpartyaccess?client_id=35b98195&redirect_uri=https%3A%2F%2Flocalhost%3A3443%2Fapi%2Foauth%2Freg" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"

**Comment by saket424** [comment]
When I use redirecturi of "https://localhost:3443/api/oauth", then I do not get the invalid_client details error but still no device IDs. I do get an authcode though which is needed to get an accesstoken but no accestoken
info: ::1 - - [Thu, 12 Apr 2018 15:17:55 GMT] "GET /api/oauth?authCode=8Z5KpYoD3bW2yZPc_IdfGsaJ2dYNiw5 HTTP/1.1" 302 62 "https://cloud.aerohive.com/thirdpartyaccess?client_id=35b98195&redirect_uri=https%3A%2F%2Flocalhost%3A3443%2Fapi%2Foauth" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36"

**Comment by tmunzer** [comment]
The redirect url has to be https://<server:port>/api/oauth/reg. If the redirect URL is different, OAuth won't work (the web app is awaiting for the oauth code on this uri only).

The "invalid_client_details" may be because the change on the developer portal was not yet propagated on the Aerohive Cloud Service.  Just configure your redirect URL with "https://localhost:3443/api/oauth/reg", wait for a few time, and try again.

**Comment by saket424** [comment]
Please update the config_example to state that the url has to end with api/oauth/reg and not api/oauth

**Comment by tmunzer** [comment]
already done :)

**Comment by saket424** [comment]
The sample works now. The correct redirect URL is "https://localhost:3443/api/oauth/reg" when the sample is run from a local laptop. Thanks @tmunzer  !
